import { haspermission } from '../extra/utils';
import { users } from './constants';
import { diamond, equilateral } from './patterns/index';
import { hasPermission, validateUser } from './utils/index';
console.log('printing equilateral triangle pattern: \n');
equilateral(10);
console.log('printing diamond pattern: \n');
diamond(5);
const status = hasPermission('getUsers', 'head-trainer', 'read');
console.log('Permission Granted status:', status);
validateUser(users);
